name: Terraform apply
run-name: Terraform apply
on:
  push:
    branches:
      - 'main'
env:
  SANDBOX_IAM_ROLE: arn:aws:iam::242906888793:role/AWS_Sandbox
jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform_plan.yml
    with:
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: ./composite_actions/setup_tf

      - name: Verify Terraform version
        run: terraform --version

      - name: Download tf plan
        working-directory: ./infra
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform apply
        working-directory: ./infra
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ needs.terraform-plan.outputs.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ needs.terraform-plan.outputs.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ needs.terraform-plan.outputs.SANDBOX_AWS_SESSION_TOKEN }}
        run: terraform apply tfplan