name: Terraform save plan
run-name: Terraform save plan
on:
  workflow_call:
    inputs:
      aws-sandbox-role-arn:
        required: false
        type: string
        default: arn:aws:iam::242906888793:role/AWS_Sandbox
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      SANDBOX_AWS_ACCESS_KEY_ID:
        description: "Access key ID"
        value: ${{ jobs.terraform-plan-infrastructure.outputs.SANDBOX_AWS_ACCESS_KEY_ID }}
      SANDBOX_AWS_SESSION_TOKEN:
        description: "Session token"
        value: ${{ jobs.terraform-plan-infrastructure.outputs.SANDBOX_AWS_SESSION_TOKEN }}
      SANDBOX_AWS_SECRET_ACCESS_KEY:
        description: "Secret access key"
        value: ${{ jobs.terraform-plan-infrastructure.outputs.SANDBOX_AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      SANDBOX_AWS_ACCESS_KEY_ID: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_ACCESS_KEY_ID }}
      SANDBOX_AWS_SESSION_TOKEN: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SESSION_TOKEN }}
      SANDBOX_AWS_SECRET_ACCESS_KEY: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: ./composite_actions/setup_tf
        with:
          terraform-version: '1.4.0'

      - name: Verify Terraform version
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create Sandbox session
        id: create-sandbox-session
        uses: ./composite_actions/sandbox_session
        with:
          sandbox-role-arn: ${{ inputs.aws-sandbox-role-arn }}

      - name: Terraform init
        working-directory: ./infra
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SESSION_TOKEN }}
        run: terraform init

      - name: Terraform plan
        working-directory: ./infra
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ steps.create-sandbox-session.outputs.SANDBOX_AWS_SESSION_TOKEN }}
        run: terraform plan -out tfplan

#      - name: Save tf plan
#        working-directory: ./infra
#        uses: actions/upload-artifact@v3
#        with:
#          name: tfplan
#          path: tfplan