name: Terraform plan on PR
run-name: Terraform plan on PR
on: [pull_request]
jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform_plan.yml
    with:
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
