name: Validate terraform files & generate plan
run-name: Validate terraform files & generate plan
#on: [workflow_dispatch]
on:
  pull_request:
    types: [opened, reopened, edited]
env:
  SANDBOX_IAM_ROLE: arn:aws:iam::242906888793:role/AWS_Sandbox
jobs:
  terraform-provision-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: eu-central-1
          role-to-assume: '${{ env.SANDBOX_IAM_ROLE }}'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        run: cd ./infra
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan