name: Validate terraform files & generate plan
run-name: Validate terraform files & generate plan
defaults:
  run:
    working-directory: ./infra
on: [pull_request, workflow_dispatch]
env:
  SANDBOX_IAM_ROLE: arn:aws:iam::242906888793:role/AWS_Sandbox
jobs:
  terraform-plan-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "1.4.0"
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Verify Terraform version
        run: terraform --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create Sandbox session
        run: |
          credentials=$(aws sts assume-role --role-arn "$SANDBOX_IAM_ROLE" --role-session-name sandbox-session)
          echo "SANDBOX_AWS_ACCESS_KEY_ID=$(echo "$credentials" | jq .Credentials.AccessKeyId -r)" >> "$GITHUB_ENV"
          echo "SANDBOX_AWS_SESSION_TOKEN=$(echo "$credentials" | jq .Credentials.SessionToken -r)" >> "$GITHUB_ENV"
          echo "SANDBOX_AWS_SECRET_ACCESS_KEY=$(echo "$credentials" | jq .Credentials.SecretAccessKey -r)" >> "$GITHUB_ENV"

      - name: Terraform init
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ env.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.SANDBOX_AWS_SESSION_TOKEN }}
          TF_LOG: DEBUG # TODO remove
        run: terraform init

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ env.SANDBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.SANDBOX_AWS_SESSION_TOKEN }}
        run: terraform plan