name: terraform validate & terraform plan
run-name: terraform validate & terraform plan
defaults:
  run:
    working-directory: ./infra
on: [pull_request]
jobs:
  terraform-plan-infrastructure:
    runs-on: ubuntu-latest
    steps:
      uses: ./.github/workflows/terraform_plan.yml
      with:
        secrets: inherit